/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchSelectionRouteImport } from './routes/branch-selection'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FacultyDashboardRouteImport } from './routes/faculty-dashboard'
import { Route as FacultyLoginRouteImport } from './routes/faculty-login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HardwareSpecializationRouteImport } from './routes/hardware-specialization'
import { Route as MtechSpecializationRouteImport } from './routes/mtech-specialization'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SelectProgramRouteImport } from './routes/select-program'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SoftwareSpecializationRouteImport } from './routes/software-specialization'
import { Route as RoadmapTrackRouteImport } from './routes/roadmap.$track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchSelectionRoute = BranchSelectionRouteImport.update({
  id: '/branch-selection',
  path: '/branch-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/faculty-dashboard',
  path: '/faculty-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLoginRoute = FacultyLoginRouteImport.update({
  id: '/faculty-login',
  path: '/faculty-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareSpecializationRoute = HardwareSpecializationRouteImport.update({
  id: '/hardware-specialization',
  path: '/hardware-specialization',
  getParentRoute: () => rootRouteImport,
} as any)
const MtechSpecializationRoute = MtechSpecializationRouteImport.update({
  id: '/mtech-specialization',
  path: '/mtech-specialization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectProgramRoute = SelectProgramRouteImport.update({
  id: '/select-program',
  path: '/select-program',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareSpecializationRoute = SoftwareSpecializationRouteImport.update({
  id: '/software-specialization',
  path: '/software-specialization',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapTrackRoute = RoadmapTrackRouteImport.update({
  id: '/roadmap/$track',
  path: '/roadmap/$track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branch-selection': typeof BranchSelectionRoute
  '/courses': typeof CoursesRoute
  '/faculty-dashboard': typeof FacultyDashboardRoute
  '/faculty-login': typeof FacultyLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hardware-specialization': typeof HardwareSpecializationRoute
  '/mtech-specialization': typeof MtechSpecializationRoute
  '/profile': typeof ProfileRoute
  '/select-program': typeof SelectProgramRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/software-specialization': typeof SoftwareSpecializationRoute
  '/roadmap/$track': typeof RoadmapTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branch-selection': typeof BranchSelectionRoute
  '/courses': typeof CoursesRoute
  '/faculty-dashboard': typeof FacultyDashboardRoute
  '/faculty-login': typeof FacultyLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hardware-specialization': typeof HardwareSpecializationRoute
  '/mtech-specialization': typeof MtechSpecializationRoute
  '/profile': typeof ProfileRoute
  '/select-program': typeof SelectProgramRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/software-specialization': typeof SoftwareSpecializationRoute
  '/roadmap/$track': typeof RoadmapTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branch-selection': typeof BranchSelectionRoute
  '/courses': typeof CoursesRoute
  '/faculty-dashboard': typeof FacultyDashboardRoute
  '/faculty-login': typeof FacultyLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hardware-specialization': typeof HardwareSpecializationRoute
  '/mtech-specialization': typeof MtechSpecializationRoute
  '/profile': typeof ProfileRoute
  '/select-program': typeof SelectProgramRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/software-specialization': typeof SoftwareSpecializationRoute
  '/roadmap/$track': typeof RoadmapTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branch-selection'
    | '/courses'
    | '/faculty-dashboard'
    | '/faculty-login'
    | '/forgot-password'
    | '/hardware-specialization'
    | '/mtech-specialization'
    | '/profile'
    | '/select-program'
    | '/settings'
    | '/signup'
    | '/software-specialization'
    | '/roadmap/$track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branch-selection'
    | '/courses'
    | '/faculty-dashboard'
    | '/faculty-login'
    | '/forgot-password'
    | '/hardware-specialization'
    | '/mtech-specialization'
    | '/profile'
    | '/select-program'
    | '/settings'
    | '/signup'
    | '/software-specialization'
    | '/roadmap/$track'
  id:
    | '__root__'
    | '/'
    | '/branch-selection'
    | '/courses'
    | '/faculty-dashboard'
    | '/faculty-login'
    | '/forgot-password'
    | '/hardware-specialization'
    | '/mtech-specialization'
    | '/profile'
    | '/select-program'
    | '/settings'
    | '/signup'
    | '/software-specialization'
    | '/roadmap/$track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchSelectionRoute: typeof BranchSelectionRoute
  CoursesRoute: typeof CoursesRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyLoginRoute: typeof FacultyLoginRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HardwareSpecializationRoute: typeof HardwareSpecializationRoute
  MtechSpecializationRoute: typeof MtechSpecializationRoute
  ProfileRoute: typeof ProfileRoute
  SelectProgramRoute: typeof SelectProgramRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SoftwareSpecializationRoute: typeof SoftwareSpecializationRoute
  RoadmapTrackRoute: typeof RoadmapTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-selection': {
      id: '/branch-selection'
      path: '/branch-selection'
      fullPath: '/branch-selection'
      preLoaderRoute: typeof BranchSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty-dashboard': {
      id: '/faculty-dashboard'
      path: '/faculty-dashboard'
      fullPath: '/faculty-dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty-login': {
      id: '/faculty-login'
      path: '/faculty-login'
      fullPath: '/faculty-login'
      preLoaderRoute: typeof FacultyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware-specialization': {
      id: '/hardware-specialization'
      path: '/hardware-specialization'
      fullPath: '/hardware-specialization'
      preLoaderRoute: typeof HardwareSpecializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mtech-specialization': {
      id: '/mtech-specialization'
      path: '/mtech-specialization'
      fullPath: '/mtech-specialization'
      preLoaderRoute: typeof MtechSpecializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-program': {
      id: '/select-program'
      path: '/select-program'
      fullPath: '/select-program'
      preLoaderRoute: typeof SelectProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-specialization': {
      id: '/software-specialization'
      path: '/software-specialization'
      fullPath: '/software-specialization'
      preLoaderRoute: typeof SoftwareSpecializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/$track': {
      id: '/roadmap/$track'
      path: '/roadmap/$track'
      fullPath: '/roadmap/$track'
      preLoaderRoute: typeof RoadmapTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchSelectionRoute: BranchSelectionRoute,
  CoursesRoute: CoursesRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyLoginRoute: FacultyLoginRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HardwareSpecializationRoute: HardwareSpecializationRoute,
  MtechSpecializationRoute: MtechSpecializationRoute,
  ProfileRoute: ProfileRoute,
  SelectProgramRoute: SelectProgramRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SoftwareSpecializationRoute: SoftwareSpecializationRoute,
  RoadmapTrackRoute: RoadmapTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
